spring.application.name=books
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
csv.import.path=/path/to/MyBooks.csv
openlibrary.base-url=https://openlibrary.org/api/books